### ISSUE TITLE
When upgrade to version 3.0.0 get error

### ISSUE THREAD

**Issue by arashkey** [Saeed-Pooyanfar/ng-persian-datepicker#43]
Thanks a lot for new version
but when I change the version of datepicker to 3.0.0 get this error in compile time
but when compile ng-persian-datepicker project everything's ok

```

ERROR in node_modules/ng-persian-datepicker/lib/ng-persian-datepicker.component.d.ts:109:21 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

109     static ɵfac: i0.ɵɵFactoryDeclaration<NgPersianDatepickerComponent, never>;
                        ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-persian-datepicker/lib/ng-persian-datepicker.component.d.ts:110:21 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵComponentDeclaration'.

110     static ɵcmp: i0.ɵɵComponentDeclaration<NgPersianDatepickerComponent, "ng-persian-datepicker", never, { "input": "input"; "dateValue": "dateValue"; "dateInitValue": "dateInitValue"; "dateIsGregorian": "dateIsGregorian"; "dateFormat": "dateFormat"; "dateGregorianFormat": "dateGregorianFormat"; "dateMin": "dateMin"; "dateMax": "dateMax"; "_timeEnable": "timeEnable"; "_timeShowSecond": "timeShowSecond"; "_timeMeridian": "timeMeridian"; "uiTheme": "uiTheme"; "uiIsVisible": "uiIsVisible"; "uiHideOnOutsideClick": "uiHideOnOutsideClick"; "uiHideAfterSelectDate": "uiHideAfterSelectDate"; "uiContainerWidth": "uiContainerWidth"; "_uiYearView": "uiYearView"; "_uiMonthView": "uiMonthView"; "uiInitViewMode": "uiInitViewMode"; "uiTodayBtnEnable": "uiTodayBtnEnable"; }, { "dateOnInit": "dateOnInit"; "dateOnSelect": "dateOnSelect"; "uiIsVisibleChange": "uiIsVisibleChange"; }, never, never>;
                        ~~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-persian-datepicker/lib/pipe/month.pipe.d.ts:6:21 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

6     static ɵfac: i0.ɵɵFactoryDeclaration<MonthPipe, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-persian-datepicker/lib/pipe/month.pipe.d.ts:7:22 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵPipeDeclaration'.

7     static ɵpipe: i0.ɵɵPipeDeclaration<MonthPipe, "month">;
                       ~~~~~~~~~~~~~~~~~
node_modules/ng-persian-datepicker/lib/ng-persian-datepicker.module.d.ts:6:21 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵFactoryDeclaration'.

6     static ɵfac: i0.ɵɵFactoryDeclaration<NgPersianDatepickerModule, never>;
                      ~~~~~~~~~~~~~~~~~~~~
node_modules/ng-persian-datepicker/lib/ng-persian-datepicker.module.d.ts:7:21 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵNgModuleDeclaration'.

7     static ɵmod: i0.ɵɵNgModuleDeclaration<NgPersianDatepickerModule, [typeof i1.NgPersianDatepickerComponent, typeof i2.MonthPipe], [typeof i3.CommonModule], [typeof i1.NgPersianDatepickerComponent]>;
                      ~~~~~~~~~~~~~~~~~~~~~
node_modules/ng-persian-datepicker/lib/ng-persian-datepicker.module.d.ts:8:21 - error TS2694: Namespace '"D:/_pro_/dotnet_core/MyWork/Insta100EasyLiker/Web/EasyLike_FrontEnd/node_modules/@angular/core/core"' has no exported member 'ɵɵInjectorDeclaration'.

8     static ɵinj: i0.ɵɵInjectorDeclaration<NgPersianDatepickerModule>;
                      ~~~~~~~~~~~~~~~~~~~~~
src/app/components/datepicker/datepicker.component.ts:14:10 - error TS2305: Module '"ng-persian-datepicker"' has no exported member 'ConfigModel'.

14 import { ConfigModel, NgPersianDatepickerComponent } from 'ng-persian-datepicker';
            ~~~~~~~~~~~
src/app/components/datepicker/datepicker.component.ts:130:23 - error TS2339: Property 'seTimeText' does not exist on type 'NgPersianDatepickerComponent'.      

130       this.datePicker.seTimeText();
                          ~~~~~~~~~~
src/app/components/datepicker/datepicker.component.ts:132:23 - error TS2339: Property 'lockInputValue' does not exist on type 'NgPersianDatepickerComponent'.  

132       this.datePicker.lockInputValue();
                          ~~~~~~~~~~~~~~
```

package.json
```

 "dependencies": {
    "@agm/core": "^1.1.0",
    "@angular/animations": "~10.0.2",
    "@angular/cdk": "^10.0.1",
    "@angular/common": "~10.0.2",
    "@angular/compiler": "~10.0.2",
    "@angular/core": "~10.0.2",
    "@angular/forms": "~10.0.2",
    "@angular/platform-browser": "~10.0.2",
    "@angular/platform-browser-dynamic": "~10.0.2",
    "@angular/router": "~10.0.2",
```

**Comment by Saeed-Pooyanfar** [comment]
V3.0.0 has some breaking changes
Some methods removed
Some files moved / renamed
That's why i jumped from v2.4.0 to v3.0.0
You must check source code and adopt your code with the new version ...
Thanks.

**Comment by arashkey** [comment]
https://stackblitz.com/edit/angular-ivy-dj2rs8
sorry but your sample code not working in version 3.0.0

**Comment by Saeed-Pooyanfar** [comment]
@arashkey 
Please forget v2.x
See example in demo component:
https://github.com/Saeed-Pooyanfar/ng-persian-datepicker/tree/master/src/app/demo
